import asyncio
import logging
import os
import random
import tempfile
import time
from pathlib import Path
from urllib.parse import urlparse
import yt_dlp

import requests
from telegram import (
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    InputMediaPhoto,
    KeyboardButton,
    ReplyKeyboardMarkup,
    ReplyKeyboardRemove,
    Update,
)
from telegram.constants import ChatAction
from telegram.error import TelegramError
from telegram.ext import (
    ApplicationBuilder,
    CallbackQueryHandler,
    CommandHandler,
    ContextTypes,
    MessageHandler,
    filters,
)
from instagram_public_downloader import INSTAGRAM_FILTER, handle_instagram_message
from youtube_downloader import YOUTUBE_FILTER, handle_youtube_message, handle_youtube_callback

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)

TOKEN = os.environ.get("TOKEN")
ADMIN_IDS = [5782729939]
MAX_MEDIA_SIZE = 49 * 1024 * 1024
SESSION_TTL_SECONDS = 20 * 60

# كوكيز تيك توك المحدثة
TIKTOK_COOKIES = """
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
.www.tiktok.com	TRUE	/	TRUE	1815775779	delay_guest_mode_vid	5
#HttpOnly_.tiktok.com	TRUE	/	FALSE	1821391819	tt-target-idc-sign	husfiQwRWUZdk8-2e0iiVNStv8gRSOxXWHQGG-N60DUoAF3RrH_DzettZGK0ueFnpauix5OOyHNTexxTrEr6eBpnJR9wKu1PIlVU5rtftjrFh4JzAlGVI21s6gwTZLa4bElAWuedKsa3YVjRe1d72ndbzsz_aAFuqf_4M6CPQnC8y95rrim3JCKzZbJDDtneqVUBL8v0tPxR8UqAH1Gegk81bvjUvXO6J3LCajOW70ye6Cj4cShNAt48afbGu2N3jqQpIdz0LmaOh9WgopqmXqZK4Tde2e56a70xp_HxTLXj1U0_yTxe4A1nhBcHwX3dmZPqLIwC5UYnWiYHS2B2iZ4jdnxTTLOBqF6wbQbdzp-z8-shmWIe2EiZUH8NnMMtlwTmNW3dDgCAawnb2VtAS7UWqZx4BpgGoeKpFtol8uWW0hrGaf4RJj_4o78AxD-ETitqP0ttumDWlERuUdMDEKLky-Mt0OxwtkZGtthmip0oE_6AqyrZyMNBZNQOY79E
.tiktok.com	TRUE	/	TRUE	1790720059	msToken	Yd3hXjcTWUKDs2RMSOud_9BPl54cobCMJwQtlg1pPHlrnCy2ovAxiTs3SZXkkeTei0TKGqxWhapVFv1sQPNkg-KA2ME_i1sgbaX0AmwW3fWwoQb9gEnoQUirc56aWvVDMCESnK-_o9Frj7Watnu4UjmORUhc4ac=
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1805407814	tt_session_tlb_tag	sttt%7C4%7CprqiMwdjdsoF8qGPLHZ06P_________79K8IUvBReC5ksTDpxeiCnCKjnVO-qn22SzFRxkWRC6k%3D
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1820959814	sid_guard	a6baa233076376ca05f2a18f2c7674e8%7C1789855809%7C15552000%7CThu%2C+18-Mar-2027+22%3A10%3A09+GMT
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1821391818	ttwid	1%7CCwtgCTLyQLG-Dm4zduQxJKVBFPJl8zRrYPALYdAFV_M%7C1789855813%7Cad294cef67daaca98db25e0d2813229491f18064d72db8236718a518f9592257
www.tiktok.com	FALSE	/	FALSE	1789942218	tt_ticket_guard_has_set_public_key	1
#HttpOnly_.tiktok.com	TRUE	/	FALSE	1805407814	store-country-code-src	uid
.www.tiktok.com	TRUE	/	TRUE	1790460622	perf_feed_cache	{%22expireTimestamp%22:1790460000000%2C%22itemIds%22:[%227670640329766210824%22%2C%227686885827439349012%22%2C%227685149387785276690%22]}
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1805407814	uid_tt	a98c5878110fec155f7740d786fcd47f1dd000d002bcfee7cff93c0d147e1aef
#HttpOnly_.tiktok.com	TRUE	/	FALSE	1805407814	store-country-sign	MEIEDNI7rBOi0ODF12RJMgQgTO3cJLiJdToP3Ug-32AQF_e1wnib8JgPGqARQEw5orkEEKcbQr0pCtCeWxB99VQm42I
www.tiktok.com	FALSE	/	FALSE	1797632059	msToken	Yd3hXjcTWUKDs2RMSOud_9BPl54cobCMJwQtlg1pPHlrnCy2ovAxiTs3SZXkkeTei0TKGqxWhapVFv1sQPNkg-KA2ME_i1sgbaX0AmwW3fWwoQb9gEnoQUirc56aWvVDMCESnK-_o9Frj7Watnu4UjmORUhc4ac=
.tiktok.com	TRUE	/	TRUE	1789942472	s_v_web_id	verify_mu8xxt4q_FX1i6oFj_AhRA_4aNd_9Tgz_EDmastYlgwQi
#HttpOnly_.tiktok.com	TRUE	/	FALSE	1805407814	store-idc	alisg
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1805407814	ssid_ucp_v1	1.0.1-KGY2YzM5YTY2ZGM1NDQ4N2YwZjU2MGExN2NkZjM4NDA4YWZjYTVmZGEKIQiFgJmuq5rrtFwQwZC81QYYswsgDDChj7zVBjgIQBJIBBADGgNteTIiIGE2YmFhMjMzMDc2Mzc2Y2EwNWYyYTE4ZjJjNzY3NGU4Mk4KIL0yxEUjBTnhcGTZNfKrys4NKmVMThqcRlC-acPAcqFEEiBDjRMmlbPRECIN82ZNH1-Q9WtZLZR004jwtH43sVWjGxgBIgZ0aWt0b2s
.www.tiktok.com	TRUE	/	TRUE	1815775817	tiktok_webapp_theme	dark
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1795039814	cmpl_token	AgQYAPPd_hfkTtKMV0J1PfSZPPDOkSocHL-WLGCkt-Y
www.tiktok.com	FALSE	/	FALSE	1797631814	last_login_method	google
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1795039814	multi_sids	6659043545036767237%3Aa6baa233076376ca05f2a18f2c7674e8
#HttpOnly_.tiktok.com	TRUE	/	FALSE	1821391829	odin_tt	b668ed18c6a2e40c701aa9ec74a7c0de8869104ee0d5c11e1efbdf2575670cbfc5c10f19c6753e57b01f40cee5f9a9958c309c27098f913a8f4e2cd41a82a5432f4c3d941d328329f000c6a9f3f0ac1b
#HttpOnly_.tiktok.com	TRUE	/	FALSE	1792447814	passport_auth_status	18ea8fd013038ebd927bc9bc8d3a4ab7%2C
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1792447814	passport_auth_status_ss	18ea8fd013038ebd927bc9bc8d3a4ab7%2C
.www.tiktok.com	TRUE	/	FALSE	1789942472	passport_fe_beating_status	true
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1805407814	sessionid	a6baa233076376ca05f2a18f2c7674e8
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1805407814	sessionid_ss	a6baa233076376ca05f2a18f2c7674e8
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1805407814	sid_tt	a6baa233076376ca05f2a18f2c7674e8
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1805407814	sid_ucp_v1	1.0.1-KGY2YzM5YTY2ZGM1NDQ4N2YwZjU2MGExN2NkZjM4NDA4YWZjYTVmZGEKIQiFgJmuq5rrtFwQwZC81QYYswsgDDChj7zVBjgIQBJIBBADGgNteTIiIGE2YmFhMjMzMDc2Mzc2Y2EwNWYyYTE4ZjJjNzY3NGU4Mk4KIL0yxEUjBTnhcGTZNfKrys4NKmVMThqcRlC-acPAcqFEEiBDjRMmlbPRECIN82ZNH1-Q9WtZLZR004jwtH43sVWjGxgBIgZ0aWt0b2s
#HttpOnly_.tiktok.com	TRUE	/	FALSE	1805407814	store-country-code	iq
.www.tiktok.com	TRUE	/	TRUE	1815775817	tiktok_webapp_theme_source	auto
#HttpOnly_.tiktok.com	TRUE	/	FALSE	1805407814	tt-target-idc	alisg
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1805407816	tt_chain_token	FQKt+F04E/9OZW95CmS+Cw==
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1789942472	tt_csrf_token	w3d09ivS-0Zglr7Pd13N99kXcogUNJUVlBoc
#HttpOnly_.tiktok.com	TRUE	/	TRUE	1805407814	uid_tt_ss	a98c5878110fec155f7740d786fcd47f1dd000d002bcfee7cff93c0d147e1aef
www.tiktok.com	FALSE	/	FALSE	1789942472	x-web-secsdk-uid	f73675d5-55b5-4c20-8398-f3ce33276be5
"""

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15",
]

class DownloadTooLarge(Exception):
    pass

def is_valid_tiktok_url(url):
    parsed = urlparse(url.strip())
    hostname = (parsed.hostname or "").lower().rstrip(".")
    return parsed.scheme == "https" and (
        hostname == "tiktok.com" or hostname.endswith(".tiktok.com")
    )

def get_cookies_file():
    if not TIKTOK_COOKIES.strip() or "Netscape HTTP Cookie File" not in TIKTOK_COOKIES:
        return None
    # تم التعديل هنا لاستخدام utf-8-sig لمنع أي خطأ في قراءة ملف الكوكيز
    cookie_file = tempfile.NamedTemporaryFile(delete=False, suffix=".txt", mode="w", encoding="utf-8-sig")
    cookie_file.write(TIKTOK_COOKIES.strip())
    cookie_file.close()
    return cookie_file.name

def fetch_tiktok_data(url):
    cookie_path = get_cookies_file()
    ydl_opts = {
        "quiet": True,
        "no_warnings": True,
        "extract_flat": False,
    }
    if cookie_path:
        ydl_opts["cookiefile"] = cookie_path

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            if not info:
                return None

            title = info.get("title") or "محتوى تيك توك"
            clean_title = "".join(
                character
                for character in title
                if character.isalnum() or character in (" ", "_", "-", "🔥")
            ).strip()

            if not clean_title:
                clean_title = "tiktok_audio"

            images = []
            if "entries" in info:
                for entry in info["entries"]:
                    if "url" in entry:
                        images.append(entry["url"])

            play_url = info.get("url")
            music_url = info.get("acodec") != "none" and info.get("url") or info.get("audio_url")

            if info.get("_type") == "playlist" and images:
                return {
                    "title": title,
                    "author": info.get("uploader", "مستخدم تيك توك"),
                    "music": None,
                    "audio_title": f"{clean_title}.mp3",
                    "images": images,
                    "play": None,
                }

            return {
                "title": title,
                "author": info.get("uploader", "مستخدم تيك توك"),
                "music": music_url,
                "audio_title": f"{clean_title}.mp3",
                "images": [],
                "play": play_url,
            }

    except Exception:
        logger.exception("Error fetching TikTok data via yt-dlp")
        return None
    finally:
        if cookie_path and os.path.exists(cookie_path):
            try:
                os.unlink(cookie_path)
            except Exception:
                pass

def download_media(url, suffix):
    temporary_path = None
    try:
        headers = {"User-Agent": random.choice(USER_AGENTS)}
        with requests.get(url, headers=headers, timeout=(8, 30), stream=True) as response:
            response.raise_for_status()

            content_length = response.headers.get("Content-Length")
            if content_length:
                try:
                    if int(content_length) > MAX_MEDIA_SIZE:
                        raise DownloadTooLarge
                except ValueError:
                    pass

            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as temporary_file:
                temporary_path = Path(temporary_file.name)
                downloaded = 0

                for chunk in response.iter_content(chunk_size=128 * 1024):
                    if not chunk:
                        continue
                    downloaded += len(chunk)
                    if downloaded > MAX_MEDIA_SIZE:
                        raise DownloadTooLarge
                    temporary_file.write(chunk)

        return temporary_path

    except Exception:
        if temporary_path:
            temporary_path.unlink(missing_ok=True)
        raise

def remember_session(context, message, user_id, url, title):
    sessions = context.application.bot_data.setdefault("download_sessions", {})
    now = time.monotonic()

    expired = [
        key
        for key, session in sessions.items()
        if now - session["created_at"] > SESSION_TTL_SECONDS
    ]
    for key in expired:
        sessions.pop(key, None)

    key = (message.chat_id, message.message_id)
    sessions[key] = {
        "user_id": user_id,
        "url": url,
        "title": title,
        "created_at": now,
    }

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_name = update.effective_user.first_name
    welcome_msg = (
        f"✦ أهلاً بك ⦗ {user_name} ⦘ 🖤\n\n"
        f"▫︎ بوت التحميل السريع 📥\n"
        f"▫︎ يوتيوب • تيك توك • إنستغرام\n\n"
        f"⚡ أرسل الرابط الآن للبدء 🔻"
    )
    await update.message.reply_text(welcome_msg)

async def admin_panel(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    if user_id not in ADMIN_IDS:
        await update.message.reply_text("❌ عذراً، هذا الأمر مخصص للمشرفين فقط.")
        return

    keyboard = [
        [KeyboardButton("📊 عدد المشتركين"), KeyboardButton("📢 بدء إذاعة 🔊")],
        [KeyboardButton("🛑 إيقاف الإذاعة 🔊"), KeyboardButton("🗑️ حذف جميع الإذاعات 🔊")],
        [KeyboardButton("-------------------------------------")],
        [KeyboardButton("🚪 إخفاء لوحة التحكم")],
    ]
    reply_markup = ReplyKeyboardMarkup(keyboard, resize_keyboard=True)
    await update.message.reply_text("👑 **مرحباً بك في لوحة تحكم البوت:**", reply_markup=reply_markup)

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id
    text = update.message.text if update.message and update.message.text else ""

    if user_id in ADMIN_IDS:
        if text == "🚪 إخفاء لوحة التحكم":
            await update.message.reply_text("🚪 تم إخفاء لوحة التحكم.", reply_markup=ReplyKeyboardRemove())
            return
        elif text.startswith(("📊", "📢", "🛑", "🗑️")) or "-------------------------------------" in text:
            await update.message.reply_text(f"⚙️ تم استقبال الأمر: {text}")
            return

    url = text.strip()
    if not is_valid_tiktok_url(url):
        await update.message.reply_text("❌ أرسل رابط تيك توك صحيحاً من فضلك.")
        return

    processing_msg = await update.message.reply_text("⏰┇يرجى الانتظار، يتم قياس حجم التحميل...")

    try:
        keyboard = [
            [InlineKeyboardButton("🎵 تحميل كملف صوتي.", callback_data="audio")],
            [InlineKeyboardButton("📥 تحميل باعلى دقه HD.", callback_data="hd_video")],
        ]
        reply_markup = InlineKeyboardMarkup(keyboard)

        tiktok_data = await asyncio.to_thread(fetch_tiktok_data, url)

        if tiktok_data:
            title = tiktok_data["title"]
            images = tiktok_data["images"]
            video_url = tiktok_data["play"]
            audio_url = tiktok_data["music"]
            caption_text = "- @G66Gbot"

            if images:
                await context.bot.send_chat_action(chat_id=update.effective_chat.id, action=ChatAction.UPLOAD_PHOTO)
                total_images = len(images)
                for i in range(0, total_images, 10):
                    batch = images[i:i + 10]
                    media_group = [
                        InputMediaPhoto(media=img_url, caption=f"- @G66Gbot - {i+idx+1}/{total_images}" if i+idx+1 == total_images else None)
                        for idx, img_url in enumerate(batch)
                    ]
                    if media_group:
                        await update.message.reply_media_group(media=media_group)
                await processing_msg.delete()
                return

            elif video_url:
                local_video_path = await asyncio.to_thread(download_media, video_url, ".mp4")
                try:
                    await context.bot.send_chat_action(chat_id=update.effective_chat.id, action=ChatAction.UPLOAD_VIDEO)
                    with local_video_path.open("rb") as video_file:
                        sent_video = await update.message.reply_video(
                            video=video_file, caption=caption_text, reply_markup=reply_markup
                        )
                    remember_session(context, sent_video, user_id, url, title)
                finally:
                    local_video_path.unlink(missing_ok=True)
                await processing_msg.delete()
                return

        await processing_msg.edit_text("⚠️┇هذا الملف لا يمكنني تحميله،\n⚠️┇لأن حجمه يتجاوز الحد المسموح.")

    except Exception:
        logger.exception("Error in handle_message")
        await processing_msg.edit_text("⚠️┇حدث خطأ أثناء معالجة الطلب.")

async def button_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    if not query or not query.message:
        return
    await query.answer()

    if query.data in ["yt_video", "yt_audio", "yt_voice"]:
        chat_id = query.message.chat_id
        yt_sessions = context.application.bot_data.get("yt_sessions", {})
        session = yt_sessions.get((chat_id, query.message.message_id))
        if not session:
            await query.message.reply_text("❌ انتهت صلاحية الجلسة.")
            return
        await handle_youtube_callback(query, context, session, query.data)
        return

    chat_id = query.message.chat_id
    sessions = context.application.bot_data.setdefault("download_sessions", {})
    session_key = (chat_id, query.message.message_id)
    session = sessions.get(session_key)

    if not session or time.monotonic() - session["created_at"] > SESSION_TTL_SECONDS or query.from_user.id != session["user_id"]:
        sessions.pop(session_key, None)
        await query.message.reply_text("❌ انتهت صلاحية الجلسة.")
        return

    url = session["url"]
    video_title = session["title"]

    if query.data == "audio":
        try:
            await query.edit_message_reply_markup(reply_markup=None)
        except TelegramError:
            pass

        status_msg = await query.message.reply_text("🔄 جاري تحميل الملف الصوتي...")
        local_audio_path = None
        try:
            tiktok_data = await asyncio.to_thread(fetch_tiktok_data, url)
            audio_link = tiktok_data.get("music") if tiktok_data else None
            if not audio_link:
                raise ValueError("Audio link unavailable")

            local_audio_path = await asyncio.to_thread(download_media, audio_link, ".mp3")
            await context.bot.send_chat_action(chat_id=chat_id, action=ChatAction.UPLOAD_VOICE)

            with local_audio_path.open("rb") as audio_file:
                await context.bot.send_audio(
                    chat_id=chat_id, audio=audio_file, title=video_title, performer="@G66Gbot", caption="- @G66Gbot"
                )
            await status_msg.delete()
        except Exception:
            logger.exception("Audio callback error")
            await status_msg.edit_text("❌ حدث خطأ أثناء تحميل الملف الصوتي.")
        finally:
            if local_audio_path:
                local_audio_path.unlink(missing_ok=True)
            sessions.pop(session_key, None)

    elif query.data == "hd_video":
        try:
            await query.edit_message_reply_markup(reply_markup=None)
        except TelegramError:
            pass

        status_msg = await query.message.reply_text("🔄 جاري إرسال الفيديو...")
        local_video_path = None
        try:
            tiktok_data = await asyncio.to_thread(fetch_tiktok_data, url)
            video_url = tiktok_data.get("play") if tiktok_data else None
            if not video_url:
                raise ValueError("Video link unavailable")

            audio_reply_markup = InlineKeyboardMarkup([[InlineKeyboardButton("🎵 تحميل كملف صوتي.", callback_data="audio")]])
            local_video_path = await asyncio.to_thread(download_media, video_url, ".mp4")
            await context.bot.send_chat_action(chat_id=chat_id, action=ChatAction.UPLOAD_VIDEO)

            with local_video_path.open("rb") as video_file:
                sent_video = await context.bot.send_video(
                    chat_id=chat_id, video=video_file, caption="- @G66Gbot", reply_markup=audio_reply_markup
                )
            remember_session(context, sent_video, query.from_user.id, url, video_title)
            await status_msg.delete()
        except Exception:
            logger.exception("HD video callback error")
            await status_msg.edit_text("⚠️حدث خطأ أثناء تحميل الفيديو.")
        finally:
            if local_video_path:
                local_video_path.unlink(missing_ok=True)
            sessions.pop(session_key, None)

def main():
    if not TOKEN:
        raise RuntimeError("TOKEN environment variable is not set.")

    app = ApplicationBuilder().token(TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("admin", admin_panel))
    app.add_handler(MessageHandler(INSTAGRAM_FILTER, handle_instagram_message))
    app.add_handler(MessageHandler(YOUTUBE_FILTER, handle_youtube_message))
    app.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), handle_message))
    app.add_handler(CallbackQueryHandler(button_callback))

    print("بوت التحميل يعمل الآن بكفاءة...")
    app.run_polling()

if __name__ == "__main__":
    main()
