import asyncio
import html
import json
import logging
import os
import re
import shutil
import tempfile
import traceback
from urllib.parse import urlencode
from urllib.request import Request, urlopen
from pathlib import Path

import youtube_dl  # الاعتماد حصراً على مكتبة youtube-dl
from telegram import InlineKeyboardButton, InlineKeyboardMarkup
from telegram.constants import ChatAction
from telegram.ext import filters

logger = logging.getLogger(__name__)

MAX_MEDIA_SIZE = 49 * 1024 * 1024
YOUTUBE_API_KEY_VARIABLE = "YOUTUBE_API_KEY"

MAX_CONCURRENT_DOWNLOADS = 2
DOWNLOAD_SEMAPHORE = asyncio.Semaphore(MAX_CONCURRENT_DOWNLOADS)
USER_DOWNLOAD_LOCKS = {}

YOUTUBE_REGEX = re.compile(
    r"(https?://)?(www\.)?(youtube\.com|youtu\.be)/(watch\?v=|shorts/|embed/)?([a-zA-Z0-9_-]+)"
)


class DownloadTooLarge(Exception):
    pass


class YoutubeFilter(filters.MessageFilter):
    def filter(self, message):
        text = message.text or message.caption or ""
        return bool(YOUTUBE_REGEX.search(text.strip()))


YOUTUBE_FILTER = YoutubeFilter()


def is_valid_youtube_url(url: str) -> bool:
    if not url:
        return False
    return bool(YOUTUBE_REGEX.search(url.strip()))


def extract_youtube_url(text: str) -> str:
    match = YOUTUBE_REGEX.search(text or "")
    if not match:
        raise ValueError("Invalid YouTube URL")
    return match.group(0)


def get_youtube_video_id(url: str) -> str:
    match = YOUTUBE_REGEX.search(url)
    if not match:
        raise ValueError("Invalid YouTube URL")
    return match.group(5)


def parse_iso8601_duration(value: str) -> int:
    match = re.fullmatch(
        r"P(?:(?P<days>\d+)D)?(?:T(?:(?P<hours>\d+)H)?(?:(?P<minutes>\d+)M)?(?:(?P<seconds>\d+)S)?)?",
        value or "",
    )
    if not match:
        return 0
    parts = match.groupdict(default="0")
    return (
        int(parts["days"]) * 86400
        + int(parts["hours"]) * 3600
        + int(parts["minutes"]) * 60
        + int(parts["seconds"])
    )


def get_user_download_lock(user_id: int) -> asyncio.Lock:
    lock = USER_DOWNLOAD_LOCKS.get(user_id)
    if lock is None:
        lock = asyncio.Lock()
        USER_DOWNLOAD_LOCKS[user_id] = lock
    return lock


def format_views(views):
    if not views:
        return "0"
    if views >= 1_000_000:
        return f"{views / 1_000_000:.1f}M"
    if views >= 1_000:
        return f"{int(views / 1_000)}K"
    return str(views)


def get_youtube_info(url: str):
    api_key = os.getenv(YOUTUBE_API_KEY_VARIABLE)
    if not api_key:
        raise RuntimeError("YOUTUBE_API_KEY is not configured")

    query = urlencode(
        {
            "part": "snippet,contentDetails,statistics",
            "id": get_youtube_video_id(url),
            "key": api_key,
        }
    )
    request = Request(
        f"https://www.googleapis.com/youtube/v3/videos?{query}",
        headers={"Accept": "application/json"},
    )
    with urlopen(request, timeout=15) as response:
        payload = json.load(response)

    items = payload.get("items", [])
    if not items:
        raise ValueError("Video was not found or is not publicly available")

    item = items[0]
    snippet = item.get("snippet", {})
    thumbnails = snippet.get("thumbnails", {})
    thumbnail = next(
        (
            thumbnails[size].get("url")
            for size in ("maxres", "standard", "high", "medium", "default")
            if thumbnails.get(size, {}).get("url")
        ),
        None,
    )
    duration = parse_iso8601_duration(item.get("contentDetails", {}).get("duration", ""))
    minutes, seconds = divmod(duration, 60)

    return {
        "title": snippet.get("title") or "فيديو يوتيوب",
        "uploader": snippet.get("channelTitle") or "غير معروف",
        "duration": duration,
        "duration_string": f"{minutes:02d}:{seconds:02d}",
        "view_count_formatted": format_views(int(item.get("statistics", {}).get("viewCount", 0))),
        "thumbnail": thumbnail,
        "url": url,
    }


def download_youtube_media(url: str, mode: str = "video"):
    format_type = "mp3" if mode in ["audio", "yt_audio", "yt_voice"] else "mp4"
    temp_dir = tempfile.mkdtemp()
    
    output_template = os.path.join(temp_dir, "media.%(ext)s")

    # إعدادات مكتبة youtube-dl الكلاسيكية مع ملف الكوكيز
    ydl_opts = {
        'format': 'bestaudio/best' if format_type == 'mp3' else 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
        'outtmpl': output_template,
        'noplaylist': True,
        'socket_timeout': 30,
        'quiet': True,
    }

    # ملف الكوكيز الخاص بك لتجاوز الحظر
    youtube_cookies_content = """
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1802726032	VISITOR_PRIVACY_METADATA	CgJJURIEGgAgFg%3D%3D
.youtube.com	TRUE	/	FALSE	1794693984	_gcl_au	1.1.75628012.1786917984.-.-.1786917985.998959808.1786917985.1786917985
#HttpOnly_.youtube.com	TRUE	/	TRUE	1824433095	__Secure-3PSID	g.a000CwkhD3aQI7Fmb0xQq1WbQ6GiyYrsx0xN7r8Cnw_C_BZHrv52M5kAzr1gq6hd1AyIOJ9LHAACgYKAbQSARUSFQHGX2MihBIAj_8S6bpkepjWh66EwRoVAUF8yKrien1OfiQ2QPj1z6NL-lzL0076
.youtube.com	TRUE	/	FALSE	1821410647	SIDCC	AKEyXzWCS-7uQaT4zcogLdbqbRyokiZvupa081peWVzPcH8nZFxETknrl1r9sH1FDQ7-gESS7A
.youtube.com	TRUE	/	FALSE	1824433095	SID	g.a000CwkhD3aQI7Fmb0xQq1WbQ6GiyYrsx0xN7r8Cnw_C_BZHrv52oZciHbFEEAuvE2-WXqNBnQACgYKATMSARUSFQHGX2Mi_LFDAW-34wjKB23gN8386RoVAUF8yKqWQJok0t69Do76EV8Rwi5b0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1821410624	__Secure-1PSIDTS	sidts-CjUBXMw41egY2Yp9XtSlKoXMlxcr10_jud8VT8HqtM0t-MjyTBOn_JvG3ElfR3SE-peaufA2rxAA
.youtube.com	TRUE	/	TRUE	1824433095	SAPISID	nG-jCKQWekLdzgXE/Ad014d1zxL8VNsamb
#HttpOnly_.youtube.com	TRUE	/	TRUE	1821410647	__Secure-1PSIDCC	AKEyXzUoILjlF_eJeVQT9vUWYJAHSMTv5A71RV8lABrdLSxioWYNXZzI7MwM0vWxUkUfCOD2bQ
#HttpOnly_.youtube.com	TRUE	/	TRUE	1824433095	SSID	AnICD_xPBcGksN8-_
.youtube.com	TRUE	/	TRUE	1824433095	__Secure-1PAPISID	nG-jCKQWekLdzgXE/Ad014d1zxL8VNsamb
#HttpOnly_.youtube.com	TRUE	/	TRUE	1824433095	__Secure-1PSID	g.a000CwkhD3aQI7Fmb0xQq1WbQ6GiyYrsx0xN7r8Cnw_C_BZHrv52eUH0CSPQInsurmhEx1MFIQACgYKASISARUSFQHGX2MilY1PU1N7vq4xv7AgZCZtzxoVAUF8yKorTzctH-GNIgdxs6RWWlyF0076
.youtube.com	TRUE	/	TRUE	1824433095	__Secure-3PAPISID	nG-jCKQWekLdzgXE/Ad014d1zxL8VNsamb
#HttpOnly_.youtube.com	TRUE	/	TRUE	1821410647	__Secure-3PSIDCC	AKEyXzWdfq469dZ_MKeR0MVF1jbqEGYq0tx_NFFlCZjm67K2HWg3utcPWxRmOkJc35P0R_p80w
#HttpOnly_.youtube.com	TRUE	/	TRUE	1821410624	__Secure-3PSIDTS	sidts-CjUBXMw41egY2Yp9XtSlKoXMlxcr10_jud8VT8HqtM0t-MjyTBOn_JvG3ElfR3SE-peaufA2rxAA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1802552721	__Secure-YNID	21.YT=lEdo40nebD2jxwEJhVTNxc9dpAmxSw0JDRXI0sYC76WdCgzpzQj0VuPAf3ser10narpVrowR4w-NKD64Gy3Y-JCkgSzPpRkGHM6bLTmtsVyAH2_NUiPGSzMCNj3ywoPOjSs2NIT-TZjD9fUTO8RtDaOSlY3cub_mIiJeCE3lnRB0XTg0kdVTzI8e1Dzv6tdHrdrN3A_xULoNvHpXR-GNwHlg6e6KVqqWklPATp-8ccbm1pFYOIjZso6cAv_Uab-Mhtbk_CbM1G95N7gKxZ3xBNFuQrdw4vxL0phz7vmidrlnRMBD_2ch09HvKMk9QqzLfqb5hoB35JCJVkYF05KA5g
.youtube.com	TRUE	/	FALSE	1821477984	_ga	GA1.1.1332346012.1786917984
.youtube.com	TRUE	/	FALSE	1821478199	_ga_VCGEPY40VB	GS2.1.s1786917984$o1$g1$t1786918199$j60$l0$h0
.youtube.com	TRUE	/	FALSE	1824433095	APISID	mP05hk4d7IqkB5HB/AQqskit86c2efP4TD
#HttpOnly_.youtube.com	TRUE	/	FALSE	1824433095	HSID	AeTzNzbjaexnaynjw
#HttpOnly_.youtube.com	TRUE	/	TRUE	1824434643	LOGIN_INFO	AFmmF2swRgIhAInmyTPuKJO4F-zat9FtqzPOumJO0EHTkBVGpZ4fGs5rAiEA422KLdHiGt4p_pBQCK-z69wuB1cHw2jEc6WfluOcRb8:QUQ3MjNmd2JlT3BwejBTT21JOVZaTkFjSGo3ZUliS2tYWW40ZFh1S1lHN09zQVJxUVdETGx2MXpsV0xBUHh4Uk5ZWHNiVFBhMWUtNHZHR2tCQzZvLVdXVEpBRzJzcTVlODFrTE1xaGNJd3VmaTlnblZpZ2ozZ1B2OHd0Zmd2VHlkVlFIbEw4Q21qMlhLUDVkQkpUSWlyaFE2Z3ZqS3Bub3hn
.youtube.com	TRUE	/	TRUE	1824434644	PREF	tz=Asia.Baghdad&f7=150&hl=ar&f4=4000000
#HttpOnly_.youtube.com	TRUE	/	TRUE	1802726032	VISITOR_INFO1_LIVE	K2aTK5Ph7bc
    """.strip()

    cookies_file_path = None
    try:
        if youtube_cookies_content:
            cookies_file_path = Path(temp_dir) / "cookies.txt"
            cookies_file_path.write_text(youtube_cookies_content, encoding="utf-8")
            ydl_opts['cookiefile'] = str(cookies_file_path)

        if format_type == "mp3":
            ydl_opts['postprocessors'] = [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': '192',
            }]

        with youtube_dl.YoutubeDL(ydl_opts) as ydl:
            info_dict = ydl.extract_info(url, download=True)
            title = info_dict.get('title', 'فيديو يوتيوب')
            duration = int(info_dict.get('duration', 180))
            
            if format_type == "mp3":
                file_path = Path(temp_dir) / "media.mp3"
            else:
                downloaded_files = list(Path(temp_dir).glob("media.*"))
                file_path = next((f for f in downloaded_files if f.suffix != '.txt'), Path(temp_dir) / "media.mp4")

            if not file_path.exists():
                files = [f for f in Path(temp_dir).iterdir() if f.name != "cookies.txt"]
                if files:
                    file_path = files[0]
                else:
                    raise FileNotFoundError("فشل العثور على الملف المحمل في المجلد المؤقت.")

            if file_path.stat().st_size > MAX_MEDIA_SIZE:
                raise DownloadTooLarge("حجم الملف يتجاوز الحد المسموح.")

        thumb_path = None
        return file_path, title, duration, thumb_path

    except Exception as e:
        print("=" * 40)
        print("❌ [DEBUG ERROR] حدث خطأ أثناء تحميل يوتيوب بـ youtube-dl:")
        traceback.print_exc()
        print("=" * 40)
        shutil.rmtree(temp_dir, ignore_errors=True)
        raise


async def handle_youtube_message(update, context):
    message = update.effective_message
    url = extract_youtube_url(message.text or message.caption or "")
    user_id = update.effective_user.id

    processing_msg = await message.reply_text("⏰┇يرجى الانتظار، جاري معالجة رابط يوتيوب...")

    try:
        info = await asyncio.to_thread(get_youtube_info, url)
        keyboard = [
            [InlineKeyboardButton("🎬 فيديو", callback_data="yt_video")],
            [
                InlineKeyboardButton("🎧 ملف صوتي", callback_data="yt_audio"),
                InlineKeyboardButton("🎙 بصمة صوتية", callback_data="yt_voice"),
            ],
        ]
        reply_markup = InlineKeyboardMarkup(keyboard)
        safe_url = html.escape(info["url"], quote=True)
        safe_title = html.escape(info["title"])
        safe_uploader = html.escape(info["uploader"])
        caption = (
            f'🎬 <a href="{safe_url}">'
            f"{safe_title}</a>\n"
            f"👤 {safe_uploader}\n"
            f'⏱ {info["duration_string"]} - 👁 {info["view_count_formatted"]}'
        )

        if info["thumbnail"]:
            try:
                sent_msg = await message.reply_photo(
                    photo=info["thumbnail"], caption=caption, parse_mode="HTML", reply_markup=reply_markup
                )
            except Exception:
                logger.warning("Unable to send YouTube thumbnail; sending text card instead", exc_info=True)
                sent_msg = await message.reply_text(
                    text=caption, parse_mode="HTML", reply_markup=reply_markup
                )
        else:
            sent_msg = await message.reply_text(
                text=caption, parse_mode="HTML", reply_markup=reply_markup
            )

        sessions = context.application.bot_data.setdefault("yt_sessions", {})
        sessions[(sent_msg.chat_id, sent_msg.message_id)] = {
            "user_id": user_id,
            "url": url,
            "title": info["title"],
        }
        await processing_msg.delete()
    except Exception:
        logger.exception("Error handling YouTube message")
        await processing_msg.edit_text("❌ حدث خطأ أثناء معالجة رابط يوتيوب.")


async def handle_youtube_callback(query, context, session_data, mode):
    chat_id = query.message.chat_id
    url = session_data["url"]
    user_id = session_data["user_id"]
    await query.answer()

    try:
        await query.message.delete()
    except Exception:
        pass

    status_msg = await context.bot.send_message(chat_id=chat_id, text="🔄 جاري التحميل، يرجى الانتظار...")
    file_path = None
    thumb_path = None

    try:
        async with get_user_download_lock(user_id):
            async with DOWNLOAD_SEMAPHORE:
                file_path, title, duration, thumb_path = await asyncio.to_thread(
                    download_youtube_media, url, mode
                )
        share_keyboard = InlineKeyboardMarkup(
            [[InlineKeyboardButton("🔀 | شارك.", switch_inline_query=f"{title}")]]
        )
        file_size_mb = f"{os.path.getsize(file_path) / (1024 * 1024):.1f}MB"
        minutes, seconds = divmod(int(duration), 60)
        time_str = f"{minutes:02d}:{seconds:02d}"

        if mode == "yt_voice":
            await context.bot.send_chat_action(chat_id=chat_id, action=ChatAction.RECORD_VOICE)
            with open(file_path, "rb") as voice_file:
                await context.bot.send_voice(
                    chat_id=chat_id, voice=voice_file, caption=f"@G66Gbot - {time_str}",
                    duration=int(duration), reply_markup=share_keyboard
                )
        elif mode == "yt_audio":
            await context.bot.send_chat_action(chat_id=chat_id, action=ChatAction.UPLOAD_VOICE)
            with open(file_path, "rb") as audio_file:
                with open(thumb_path, "rb") if thumb_path and thumb_path.exists() else _NullContext() as thumb_file:
                    await context.bot.send_audio(
                    chat_id=chat_id, audio=audio_file, title=title, performer="@G66Gbot",
                    duration=int(duration), thumbnail=thumb_file,
                    caption=f"@G66Gbot - {time_str}, {file_size_mb}", reply_markup=share_keyboard
                )
        else:
            await context.bot.send_chat_action(chat_id=chat_id, action=ChatAction.UPLOAD_VIDEO)
            with open(file_path, "rb") as video_file:
                await context.bot.send_video(
                    chat_id=chat_id, video=video_file, caption=f"@G66Gbot - {time_str}, {file_size_mb}",
                    duration=int(duration), reply_markup=share_keyboard
                )
        await status_msg.delete()
    except DownloadTooLarge:
        await status_msg.edit_text("⚠️┇هذا الملف لا يمكنني تحميله، لأن حجمه يتجاوز ( 50 MB ).")
    except Exception:
        logger.exception("Error in YouTube callback process")
        await status_msg.edit_text("❌ حدث خطأ أثناء التحميل.")
    finally:
        if file_path:
            shutil.rmtree(file_path.parent, ignore_errors=True)


class _NullContext:
    def __enter__(self):
        return None

    def __exit__(self, exc_type, exc_value, traceback):
        return False
